language: ruby
sudo: false
cache: bundler

before_install:
  - gem install bundler

script: bundle exec rake

rvm:
  - 2.5.5
  - 2.7.2
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
